<?php
declare (strict_types = 1);

namespace app\admin\model;

use think\Db;
use think\Model;
use think\model\Collection;


class buglist extends Model
{
    
    //
//    public static function getUsers():Collection{
//        return self::select();
//    }
//    public static function create(array $data, array $allowField = [], bool $replace = false): Model
//    {
//        return parent::create($data, $allowField, $replace); // TODO: Change the autogenerated stub
//    }
    public static function get_all():Collection{
        $search=buglist::Where('bug_id','>',0)->select();
        return $search;
    }

    public static function search_id_bug(int $id):Collection{
        $search=buglist::Where('bug_id',$id)->select();
        return $search;
    }
    public static function search_name_bug(String $name):Collection{
        $search=buglist::Where('bug_name',$name)->select();
        return $search;
    }

}
