<?php
declare (strict_types = 1);

namespace app\admin\model;

use think\Db;
use think\Model;
use think\model\Collection;


class user extends Model
{
    
    //
    public static function getUsers():Collection{
        return self::select();
    }
    public static function create(array $data, array $allowField = [], bool $replace = false): Model
    {
        return parent::create($data, $allowField, $replace); // TODO: Change the autogenerated stub
    }
    public static function get_all():Collection{
        $search=user::Where('user_id','>',0)->select();
        return $search;
    }

    public static function search_id_user(int $id):Collection{
        $search=user::Where('user_id',$id)->select();
        return $search;
    }
    public static function search_name_user(String $name):Collection{
        $search=user::Where('name',$name)->select();
        return $search;
    }

}
